backend:
  name: git-gateway
  branch: main # dein Branch

media_folder: "static/images/uploads" # hochgeladene Bilder
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Text", name: "body", widget: "markdown" }
      - { label: "Zusammenfassung", name: "summary", widget: "string", required: false }
