title: Mein Blog
description: Blog für Coaching Website
baseurl: "/coaching_website_uli/blog"  # GitHub Pages Projektseite
url: "https://iccycling.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

# Damit SCSS aus _sass geladen wird
sass:
  sass_dir: _sass
