baseURL = "https://iccycling.github.io/coaching_website_uli/blog/"       # Basis für relative URLs
languageCode = "de-DE"
title = "Blog"
theme = "ananke"

# Empfohlen: lieber false als true
relativeURLs = false
canonifyURLs = true


[pagination]
  disableAliases = true
  pagerSize = 6
  path = "page"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"