backend:
  name: git-gateway
  branch: main

media_folder: ""      # Bilder landen direkt im Post-Ordner
public_folder: ""     # relative Pfade funktionieren automatisch

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    media_folder: ""        # -> Bilder im gleichen Ordner wie index.md speichern
    public_folder: ""       # -> relative Pfade verwenden
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - label: "Inhalt"
        name: "body"
        widget: "markdown"
        hint: |
          ✍️ Schreibe hier deinen Beitrag in Markdown.
          Beispiel Bild einfügen:
          ![Alt-Text](foto1.jpg)





# CMS-Vorschau CSS einbinden
editor:
  preview: true
  styles:
    - /css/cms-preview.css
